environment:
  dotnetcore_version: 2.0.3

init:
- ps: $env:isVs2017 = 'false'
- ps: if (test-path "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community") { $env:isVs2017 = 'true' }
- ps: if ($env:isVs2017 -eq 'true') { $env:dotnetcore_version = '2.0.3' }

test_script:
- ps: $result = (cmd /c dotnet new console)
- ps: $result
- ps: if ($result[1] -eq 'Welcome to .NET Core!') { throw "Welcome to .NET Core message found!" }
- ps: .\check-dotnet-core.ps1
- test.cmd

build: off
