environment:
  dotnetcore_version: 2.0.0

test_script:
- ps: $result = (cmd /c dotnet new console)
- ps: if ($result[1] -eq 'Welcome to .NET Core!') { throw "Welcome to .NET Core message found!" }
- ps: .\check-dotnet-core.ps1
- test.cmd

build: off
