environment:
  dotnetcore_version: 1.0.0-preview2-003131

before_build:
- ps: .\check-dotnet-core.ps1
  
build_script:
- cd WebAppDotNetCore100
- dotnet restore
- msbuild
- cd ..
- cd WebAppDotNetCore101
- dotnet restore
- msbuild
- cd ..